name: vamp-offline-env
dependencies:
  - python=3.10
  - flake8
  - pip
  - pip:
      - requests
      - pillow
      - pdf2image
      - pytesseract
      - pikepdf
      - pdfplumber
      - openpyxl
      - chardet
      - pandas 
